#!/usr/bin/env bash
set -euo pipefail

# =========================
# Kopia Interactive Manager
# (Pop!_OS / Ubuntu / Debian ready)
# =========================

# --------- UI helpers ----------
if command -v tput >/dev/null 2>&1; then
  BOLD="$(tput bold)"; DIM="$(tput dim)"; RESET="$(tput sgr0)"
  RED="$(tput setaf 1)"; GREEN="$(tput setaf 2)"; YELLOW="$(tput setaf 3)"
  BLUE="$(tput setaf 4)"; MAGENTA="$(tput setaf 5)"; CYAN="$(tput setaf 6)"
else
  BOLD=""; DIM=""; RESET=""
  RED=""; GREEN=""; YELLOW=""; BLUE=""; MAGENTA=""; CYAN=""
fi

ok()    { echo "${GREEN}${BOLD}[OK]${RESET} $*"; }
info()  { echo "${CYAN}${BOLD}[i]${RESET} $*"; }
warn()  { echo "${YELLOW}${BOLD}[!]${RESET} $*"; }
err()   { echo "${RED}${BOLD}[X]${RESET} $*" >&2; }

pause() { read -r -p "Appuyez sur Entrée pour continuer... " _; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || { err "Commande manquante: $1"; return 1; }
}

require_sudo() {
  if ! command -v sudo >/dev/null 2>&1; then
    err "sudo n'est pas installé. Installez-le puis relancez."
    return 1
  fi
  if ! sudo -n true 2>/dev/null; then
    info "Sudo requis (vous devrez peut-être entrer votre mot de passe)."
    sudo true
  fi
}

# --------- OS detection ----------
is_apt_based() {
  # True si distro Debian/Ubuntu-like (inclut Pop!_OS via ID_LIKE)
  if [[ -f /etc/os-release ]]; then
    # shellcheck disable=SC1091
    source /etc/os-release
    case "${ID:-}" in
      ubuntu|debian|pop|pop-os) return 0 ;;
    esac
    if [[ "${ID_LIKE:-}" == *ubuntu* || "${ID_LIKE:-}" == *debian* ]]; then
      return 0
    fi
  fi
  return 1
}

# --------- State ----------
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/kopia-menu"
CONFIG_FILE="$CONFIG_DIR/config.env"
mkdir -p "$CONFIG_DIR"

# shellcheck disable=SC1090
[[ -f "$CONFIG_FILE" ]] && source "$CONFIG_FILE" || true

save_config() {
  cat >"$CONFIG_FILE" <<EOF
# Generated by kopia-menu
REPO_TYPE="${REPO_TYPE:-}"
REPO_PATH="${REPO_PATH:-}"
EOF
  ok "Configuration sauvegardée: $CONFIG_FILE"
}

# --------- Kopia helpers ----------
kopia_installed() { command -v kopia >/dev/null 2>&1; }

kopia_status() {
  if ! kopia_installed; then
    echo "Kopia: ${RED}non installé${RESET}"
    return 0
  fi
  local v
  v="$(kopia --version 2>/dev/null || true)"
  echo "Kopia: ${GREEN}installé${RESET} ${DIM}($v)${RESET}"

  if kopia repository status >/dev/null 2>&1; then
    echo "Repository: ${GREEN}connecté${RESET}"
  else
    echo "Repository: ${YELLOW}non connecté${RESET}"
  fi
}

install_dependencies_apt() {
  require_sudo
  info "Installation des dépendances (curl, gpg, apt-transport-https)..."
  sudo apt-get update -y
  sudo apt-get install -y curl gpg apt-transport-https ca-certificates
  ok "Dépendances installées."
}

install_kopia_debian_ubuntu() {
  require_sudo
  install_dependencies_apt

  info "Installation Kopia (Debian/Ubuntu/Pop!_OS) via dépôt officiel..."
  sudo install -d -m 0755 /etc/apt/keyrings

  # Key + repo
  curl -fsSL https://kopia.io/signing-key | sudo gpg --dearmor -o /etc/apt/keyrings/kopia.gpg
  echo "deb [signed-by=/etc/apt/keyrings/kopia.gpg] http://packages.kopia.io/apt/ stable main" \
    | sudo tee /etc/apt/sources.list.d/kopia.list >/dev/null

  sudo apt-get update -y
  sudo apt-get install -y kopia

  ok "Kopia installé."
}

install_kopia_generic() {
  warn "Installation automatique non disponible pour votre OS/distro."
  echo "Options:"
  echo "  - Pop!_OS / Ubuntu / Debian: supporté via APT (ce script le fait automatiquement)"
  echo "  - Sinon: installez Kopia depuis https://kopia.io (binaire/paquet), puis relancez ce script."
  return 1
}

install_kopia() {
  if kopia_installed; then
    ok "Kopia est déjà installé."
    return 0
  fi

  if is_apt_based; then
    install_kopia_debian_ubuntu
    return 0
  fi

  install_kopia_generic
  return 1
}

repo_create_filesystem() {
  need_cmd kopia

  read -r -p "Chemin du repository (ex: /mnt/backup/kopia-repo): " path
  if [[ -z "$path" ]]; then
    err "Chemin vide."
    return 1
  fi

  mkdir -p "$path"
  info "Création du repository Kopia (filesystem) dans: $path"
  kopia repository create filesystem --path "$path"

  REPO_TYPE="filesystem"
  REPO_PATH="$path"
  save_config
  ok "Repository créé et connecté."
}

repo_connect_filesystem() {
  need_cmd kopia

  read -r -p "Chemin du repository existant (ex: /mnt/backup/kopia-repo): " path
  if [[ -z "$path" ]]; then
    err "Chemin vide."
    return 1
  fi
  if [[ ! -d "$path" ]]; then
    err "Le dossier n'existe pas: $path"
    return 1
  fi

  info "Connexion au repository (filesystem): $path"
  kopia repository connect filesystem --path "$path"

  REPO_TYPE="filesystem"
  REPO_PATH="$path"
  save_config
  ok "Repository connecté."
}

repo_disconnect() {
  need_cmd kopia
  if kopia repository status >/dev/null 2>&1; then
    kopia repository disconnect
    ok "Repository déconnecté."
  else
    warn "Aucun repository connecté."
  fi
}

snapshot_create() {
  need_cmd kopia
  if ! kopia repository status >/dev/null 2>&1; then
    err "Aucun repository connecté. Faites d'abord 'Créer/Connecter repo'."
    return 1
  fi

  read -r -p "Dossier à sauvegarder (ex: /home/$USER/Documents): " src
  if [[ -z "$src" ]]; then
    err "Chemin vide."
    return 1
  fi
  if [[ ! -e "$src" ]]; then
    err "Le chemin n'existe pas: $src"
    return 1
  fi

  read -r -p "Description optionnelle (Entrée pour ignorer): " desc || true
  info "Création snapshot..."
  if [[ -n "${desc:-}" ]]; then
    kopia snapshot create "$src" --description "$desc"
  else
    kopia snapshot create "$src"
  fi
  ok "Snapshot créé."
}

snapshot_list() {
  need_cmd kopia
  if ! kopia repository status >/dev/null 2>&1; then
    err "Aucun repository connecté."
    return 1
  fi

  info "Snapshots:"
  kopia snapshot list
}

snapshot_restore() {
  need_cmd kopia
  if ! kopia repository status >/dev/null 2>&1; then
    err "Aucun repository connecté."
    return 1
  fi

  echo "Astuce: utilise 'kopia snapshot list' pour trouver l'ID."
  read -r -p "Snapshot ID à restaurer: " sid
  if [[ -z "$sid" ]]; then
    err "ID vide."
    return 1
  fi

  read -r -p "Chemin de restauration (ex: /tmp/restore): " target
  if [[ -z "$target" ]]; then
    err "Chemin cible vide."
    return 1
  fi
  mkdir -p "$target"

  info "Restauration..."
  kopia snapshot restore "$sid" --target-path "$target"
  ok "Restauration terminée dans: $target"
}

maintenance_run() {
  need_cmd kopia
  if ! kopia repository status >/dev/null 2>&1; then
    err "Aucun repository connecté."
    return 1
  fi

  info "Maintenance (peut prendre du temps)..."
  if kopia help maintenance >/dev/null 2>&1; then
    # Most common on current versions:
    kopia maintenance run
    ok "Maintenance terminée."
  else
    warn "Votre version Kopia ne supporte pas 'maintenance' (ou commande différente)."
    warn "Montrez-moi: kopia --version && kopia help"
    return 1
  fi
}

show_repo_info() {
  need_cmd kopia
  if kopia repository status >/dev/null 2>&1; then
    kopia repository status
  else
    warn "Aucun repository connecté."
  fi

  if [[ -n "${REPO_TYPE:-}" || -n "${REPO_PATH:-}" ]]; then
    echo
    info "Config script:"
    echo "  REPO_TYPE=${REPO_TYPE:-}"
    echo "  REPO_PATH=${REPO_PATH:-}"
    echo "  Fichier config: $CONFIG_FILE"
  fi
}

# --------- Main menu ----------
print_header() {
  clear || true
  echo "${BOLD}${MAGENTA}========================================${RESET}"
  echo "${BOLD}${MAGENTA}        Kopia Interactive Menu          ${RESET}"
  echo "${BOLD}${MAGENTA}========================================${RESET}"
  echo
  kopia_status
  echo
}

menu() {
  echo "${BOLD}1) Installer Kopia${RESET}"
  echo "${BOLD}2) Installer dépendances (curl/gpg)${RESET}"
  echo "${BOLD}3) Créer un repository (filesystem/local/NAS monté)${RESET}"
  echo "${BOLD}4) Connecter un repository existant (filesystem)${RESET}"
  echo "${BOLD}5) Déconnecter repository${RESET}"
  echo "${BOLD}6) Créer un snapshot (backup)${RESET}"
  echo "${BOLD}7) Lister snapshots${RESET}"
  echo "${BOLD}8) Restaurer un snapshot${RESET}"
  echo "${BOLD}9) Lancer maintenance${RESET}"
  echo "${BOLD}10) Infos repository / config${RESET}"
  echo "${BOLD}0) Quitter${RESET}"
  echo
}

main_loop() {
  while true; do
    print_header
    menu
    read -r -p "Choisissez une option: " choice
    echo
    case "${choice:-}" in
      1) install_kopia || true; pause ;;
      2)
        if is_apt_based; then
          install_dependencies_apt || true
        else
          warn "Option dépendances disponible seulement sur Debian/Ubuntu/Pop!_OS."
        fi
        pause
        ;;
      3) repo_create_filesystem || true; pause ;;
      4) repo_connect_filesystem || true; pause ;;
      5) repo_disconnect || true; pause ;;
      6) snapshot_create || true; pause ;;
      7) snapshot_list || true; pause ;;
      8) snapshot_restore || true; pause ;;
      9) maintenance_run || true; pause ;;
      10) show_repo_info || true; pause ;;
      0) info "Au revoir."; exit 0 ;;
      *) warn "Option invalide."; pause ;;
    esac
  done
}

main_loop